name: Frontend Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ secrets.PRODUCTION_API_URL }}

      # Add the timestamp step here
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      # Create Release step
           # Create Release step
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: frontend-build-${{ steps.timestamp.outputs.timestamp }}
          release_name: "Frontend Build ${{ steps.timestamp.outputs.timestamp }}"
          body: "Automated release of frontend build."
          draft: false
          prerelease: false
          token: ${{ secrets.ACTION_KEY }}  # Use your secret token here


      # Upload the frontend build
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/
          asset_name: frontend-build-${{ steps.timestamp.outputs.timestamp }}.zip
          asset_content_type: application/zip

      # Store the artifact name in a repository variable
      - name: Update Latest Build Info
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.ACTION_KEY }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ap45/library-management-frontend/actions/variables/LATEST_BUILD \
          -d "{\"name\":\"LATEST_BUILD\",\"value\":\"frontend-build-${{ steps.timestamp.outputs.timestamp }}\"}"

      # Trigger Backend Workflow
      - name: Trigger Backend Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTION_KEY }}
          repository: ap45/library-management-backend
          event-type: trigger_backend
          client-payload: '{"build_id": "frontend-build-${{ steps.timestamp.outputs.timestamp }}"}'
